# Default values for marcstreeterdev-frontend
# This is a YAML-formatted file.

# Global configuration
global:
  environment: production

# Replica count
replicaCount: 1

# Image configuration
image:
  repository: react-app
  tag: latest
  pullPolicy: IfNotPresent

# Deployment configuration
deployment:
  app:
    probePath: /marcstreeterdev-frontend/
  storybook:
    probePath: /marcstreeterdev-frontend/storybook

# Service configuration
service:
  type: ClusterIP
  app:
    port: 5173
    targetPort: 5173
  storybook:
    port: 6006
    targetPort: 6006

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: frontend.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource limits
resources:
  configMapName: marcstreeterdev-frontend-config
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 2Gi
    cpu: 700m



# Environment variables
env: []

# Development configuration (only mode supported)
dev:
  enabled: true
  service:
    port: 5173
    targetPort: 5173
  buildArgs:
    ENABLE_TESTING: true
    ENABLE_LINTING: true
    ENABLE_DEBUG: true
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m 